### ISSUE TITLE
在判断class和struct相等的时候，如果某个属性为null，会报错

### ISSUE THREAD

**Issue by tzm1119** [lamondlu/ObjectEquality#1]
![Uploading image.png…]()
建议在所有调用 prop.GetValue()后，判断一下，值是否为null,如果为null直接判断就行了

**Comment by tzm1119** [comment]
public bool IsEqual(object source, object target)
        {
            var type = source.GetType();

            if (ObjectEquality.ReferenceObjects.Any(p => p == source || p == target))
            {
                throw new CycleReferenceException();
            }

            ObjectEquality.ReferenceObjects.Add(source);
            ObjectEquality.ReferenceObjects.Add(target);

            foreach (var prop in type.GetProperties())
            {
                
                var v = prop.GetValue(source);
                //要判断是否为null
                if (v!=null)
                {
                    var equality = EqualityCollection.Equalities.First(p => p.MatchCondition(v));

                    var result = equality.IsEqual(prop.GetValue(source), prop.GetValue(target));

                    if (!result)
                    {
                        return false;
                    }
                }
                else
                {
                    return prop.GetValue(target) == v;
                }
               
            }

            return true;
        }

**Comment by lamondlu** [comment]
你说的很对，这个我改一下。
已发布1.0.7版本 @tzm1119
